(in-package :kobbweb)

(declaim (inline is-hex-char) (optimize (debug 0) (speed 3) (safety 0)))
(defun is-hex-char (c)
 (declare (type character c))
 (let ((code (char-code c)))
  (or (and (>= code (char-code #\0)) (<= code (char-code #\9)))
      (and (>= code (char-code #\a)) (<= code (char-code #\f))))
 )
)

(declaim (inline contains-only-hex-chars))
(defun contains-only-hex-chars (string)
 (declare (type simple-string string))
 (labels ((recursive-contains-only-hex-chars (str i length)
           (declare (type fixnum i length)
                    (type simple-string str))
           (if (= i length)
               t
               (if (is-hex-char (char str i))
                   (recursive-contains-only-hex-chars str (1+ i) length)
                   nil))))
  (recursive-contains-only-hex-chars string 0 (length string)))
)

(defun resolve-alias (alias)
 (assert nil)
)

(defun to-uuid (uuid-or-alias)
 (declare (type simple-string uuid-or-alias))
 (if (and (= (length uuid-or-alias) 32)
          (contains-only-hex-chars uuid-or-alias))
  (hex-string-to-byte-vector uuid-or-alias)
  (resolve-alias uuid-or-alias)
 )
)

(defun content-get-user-id (json-data)
 (if *session*
  (session-value 'id *session*)
  (let ((email (cdr (assoc :email json-data))))
   (if (null email)
       nil
       (with-connection *db-connection-parameters*
        (fetch-user-id email))
   )
  )
 )
)

(defun create-json-item (item)
 (let ((json-assoc '()))
  (push '(:success . "true") json-assoc)
  (push `(:parent . ,(byte-vector-to-hex-string (item-parent-uuid item))) json-assoc)
  (push `(:content-ref . ,(byte-vector-to-hex-string (item-content-ref item))) json-assoc)
  (push `(:children . ,(item-get-list-as-strings item)) json-assoc)
  (push `(:id . ,(byte-vector-to-hex-string (item-uuid item))) json-assoc)
  (json:encode-json-to-string json-assoc)
 )
)

(defun content-handle-get (uuid json-data)
 (assert (null json-data))
 (let ((item (item-load uuid))
       (user-id (content-get-user-id json-data)))
  (if (null user-id)
      (progn
            (setf (return-code*) +http-forbidden+)
            "Forbidden!")
      (if (null item)
          (progn
                (setf (return-code*) +http-not-found+)
                "Not found!")
          (if (acl-is-member-of (item-acl-ref item) user-id)
              (create-json-item item)
              (progn
                    (setf (return-code*) +http-forbidden+)
                    "Forbidden!")
          )
      )
  )
 )
)

(defun content-record-new-post (user-id item)
 (with-connection *db-connection-parameters*
  (execute (:insert-into 'posts :set 'user_id user-id 'item_id (byte-vector-to-hex-string (item-uuid item)))))
)

(defvar *successful-post-response* (json:encode-json-to-string '((:success . "true"))))
(defun content-handle-post (uuid json-data)
 (assert (not (null json-data)))
 (let* ((user-id (content-get-user-id json-data))
        (content-ref (hex-string-to-byte-vector (cdr (assoc :data json-data))))
        (item (item-create user-id uuid content-ref)))
  (content-record-new-post user-id item)
  (create-json-item item)
 )
)

(defun content-handle-delete (parent-uuid json-data)
 (let* ((child (cdr (assoc :child json-data)))
        (child-uuid (to-uuid child)))
  (if (item-remove-from-list parent-uuid child-uuid)
      *successful-post-response*
      (setf (return-code*) +http-bad-request+))
 )
)

(defun content-handler (uri)
 (let* ((req (request-method* *request*))
        (uuid-or-alias-string (cadr uri))
        (uuid (if (not (null uuid-or-alias-string))
                  (to-uuid uuid-or-alias-string)
                  *null-uuid*))
        (raw-json-string (octets-to-string (raw-post-data :request *request*) :external-format :utf8))
        (json-post-data (if (or (null raw-json-string) (string= raw-json-string "")) 
                            nil
                            (json:decode-json-from-string raw-json-string))))
  (cond ((eq req :get) (content-handle-get uuid json-post-data))
        ((eq req :post) (content-handle-post uuid json-post-data))
        ((eq req :delete) (content-handle-delete uuid json-post-data))
        (t (progn 
                 (setf (return-code*) +http-bad-request+)
                 "Bad request!"))
  )
 )
)

