(in-package :kobbweb)

(defun data-handle-get (ref)
 (if (null ref)
  (setf (return-code*) +http-not-found+)
  (let ((path (make-pathname :directory '(:relative "data" "data") :name ref)))
   (if (probe-file path)
       (handle-static-file path)
       (setf (return-code*) +http-not-found+)
   )
  )
 )
)

(defun data-handle-post ()
 (let* ((raw-json-string (octets-to-string (raw-post-data :request *request*) :external-format :utf8))
        (json (if (or (null raw-json-string) (string= raw-json-string "")) 
                  nil 
                  (json:decode-json-from-string raw-json-string))))
  (if (null json)
   (setf (return-code*) +http-bad-request+)
   (let ((data (cdr (assoc :data json))))
    (if (null data)
        (setf (return-code*) +http-bad-request+)
        (byte-vector-to-hex-string (data-store-string data))
    )
   )
  )
 )
)

(defun data-handler (uri)
 (let ((ref (cadr uri))
       (req (request-method* *request*)))
  (cond ((eq req :get) (data-handle-get ref))
        ((eq req :post) (data-handle-post))
        (t (setf (return-code*) +http-method-not-allowed+)))
 )
)

