(in-package :kobbweb)

(defun data-handler (uri)
 (let ((ref (cadr uri)))
  (if (null ref)
   (setf (return-code*) +http-not-found+)
   (let ((path (make-pathname :directory '(:relative "data" "data") :name ref)))
    (if (probe-file path)
     (handle-static-file path)
     (setf (return-code*) +http-not-found+)
    )
   )
  )
 )
)
